name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  MODEL: qwen2.5-coder:3b
  NO_PROXY: "127.0.0.1,localhost"

jobs:
  review:
    name: LLM Code Review (Ollama)
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Start Ollama in Docker
        run: |
          docker run -d --name ollama -p 11434:11434 -v ollama:/root/.ollama ollama/ollama:latest
          echo "Esperando a que Ollama escuche..."
          for i in $(seq 1 40); do
            curl -sS http://127.0.0.1:11434/api/tags >/dev/null && break
            sleep 2
          done

      - name: Pull model
        run: |
          docker exec ollama ollama pull "${MODEL}"
          docker exec ollama ollama list

      - name: Smoke test
        run: |
          curl -sS -X POST http://127.0.0.1:11434/api/chat \
            -H "Content-Type: application/json" \
            -d '{"model":"'${MODEL}'","stream":false,"messages":[{"role":"user","content":"say ok"}]}' \
            | head -c 200

      # --- SOLO PR: calcula archivos cambiados ---
      - name: Collect changed files (PR only)
        id: changed
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const pr = context.payload.pull_request;
            const per_page = 100;
            let page = 1, files = [];
            while (true) {
              const { data } = await github.rest.pulls.listFiles({
                ...context.repo, pull_number: pr.number, per_page, page
              });
              files.push(...data);
              if (data.length < per_page) break;
              page++;
            }
            const paths = files
              .filter(f => !['removed'].includes(f.status))
              .map(f => f.filename)
              .filter(p => !p.match(/\.(png|jpe?g|gif|webp|pdf|zip|ico|wasm|exe|dll|so)$/i));
            fs.writeFileSync('changed-files.txt', paths.join('\n'));
            core.setOutput('count', String(paths.length));
            core.setOutput('path', 'changed-files.txt');

      - name: Debug count
        run: |
          echo "Changed count: ${{ steps.changed.outputs.count }}"

      # --- PR con archivos cambiados -> usa file_list_path ---
      - name: Run Ollama Code Review (PR changed files)
        if: ${{ github.event_name == 'pull_request' && steps.changed.outputs.count != '0' }}
        uses: bernherre/checkwithai/action-ollama-codereview@v1.0.3
        with:
          model: ${{ env.MODEL }}
          server_url: http://127.0.0.1:11434
          file_list_path: ${{ steps.changed.outputs.path }}
          exclude_glob: |
            node_modules/**
            dist/**
          fail_on_critica: "true"
          retention_days: "7"

      # --- Fallback: push o PR sin cambios -> usa glob ---
      - name: Run Ollama Code Review (glob fallback)
        if: ${{ github.event_name != 'pull_request' || steps.changed.outputs.count == '0' }}
        uses: bernherre/checkwithai/action-ollama-codereview@v1.0.3
        with:
          model: ${{ env.MODEL }}
          server_url: http://127.0.0.1:11434
          file_glob: "src/**/*.{ts,tsx,js,jsx,py,cs,java,go,rs}"
          exclude_glob: |
            node_modules/**
            dist/**
          fail_on_critica: "true"
          retention_days: "7"

      - name: Upload review artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama-review
          path: ollama-review-report/**
          retention-days: 7

      - name: Dump Ollama logs on failure
        if: failure()
        run: docker logs --tail 200 ollama || true

  build:
    name: Build static site
    needs: review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install
        run: npm ci || npm i
      - name: Build
        run: npm run build
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
